Aips/Controllers/AssistantController.cs
using BL;
using BL.Assistant;
using EntityClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Aips.Controllers
{
    [Authorize(Roles="Assistant, Administrator")]
    public class AssistantController : Controller
    {
        private Validator AssistantValidator;
        private Functions AssistantFunctions;

        public AssistantController()
        {
            AssistantValidator = new Validator();
            AssistantFunctions = new Functions();
        }

        public ActionResult Index()
        {
            return View("Dashboard");
        }

        public async Task<ActionResult> AllLabs()
        {
            try
            {
                List<LabViewModel> model = new List<LabViewModel>();

                Queries query = new Queries();
                string assistantId = query.GetUserIdByUsername(User.Identity.Name);
                foreach (Lab lab in await query.GetAllLabsForAssistant(assistantId))
                {
                    model.Add(new LabViewModel()
                    {
                        LabId = lab.LabId,
                        StartTime = lab.ScheduledClassroom.ScheduleStart,
                        EndTime = lab.ScheduledClassroom.ScheduleEnd,
                        SubjectId = lab.SubjectId,
                        Subject = lab.Subject,
                        SchoolDay = lab.ScheduledClassroom.SchoolDay
                    });
                }


                return View(model);
            }
            catch (Exception e)
            {
                return Helpers.ControllerExtensions.RedirectToError(this, e);
            }
        }

        public async Task<ActionResult> MarkLabPresence(int labId)
        {
            try
            {
                TempData.Remove("LabId");
                TempData.Add("LabId", labId);
                Queries query = new Queries();
                ViewBag.Lab = await query.GetLab(labId);
                List<MarkLabPresenceViewModel> model = await GetLabPresenceViewModel(labId);

                return View(model);
            }
            catch (Exception e)
            {
                return Helpers.ControllerExtensions.RedirectToError(this, e);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MarkLabPresence(string ids)
        {
            try
            {
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                string[] array = (string[])serializer.Deserialize(ids, typeof(string[]));
                int labId = (int)TempData["LabId"];

                ValidationResult result = await AssistantFunctions.MarkLabPresence(array, labId);
                if (result)
                {
                    return RedirectToAction("Index");
                }

                Queries query = new Queries();
                ViewBag.Lab = await query.GetLab(labId);
                List<MarkLabPresenceViewModel> model = await GetLabPresenceViewModel(labId);

                return View(model);
            }
            catch (Exception e)
            {
                return Helpers.ControllerExtensions.RedirectToError(this, e);
            }
        }
        private async Task<List<MarkLabPresenceViewModel>> GetLabPresenceViewModel(int labId)
        {
            Queries query = new Queries();
            List<User> assignedStudents = await query.GetStudentsForLab(labId);

            List<MarkLabPresenceViewModel> model = new List<MarkLabPresenceViewModel>();

            foreach (User student in assignedStudents)
            {
                model.Add(new MarkLabPresenceViewModel()
                {
                    StudentId = student.Id,
                    StudentFirstName = student.FirstName,
                    StudentLastName = student.LastName
                });
            }
            return model;
        }
    }
}

Aips/Views/Assistant/AllLabs.cshtml
@model IEnumerable<EntityClasses.LabViewModel>

@{
    ViewBag.Title = "All labs";
}

<h2>All labs</h2>

<table class="table table-responsive table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubjectId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SchoolDay)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.Subject.Title
        </td>
        <td>
            @item.StartTime.ToShortTimeString()
        </td>
        <td>
            @item.EndTime.ToShortTimeString()
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SchoolDay.Name)
        </td>
        <td>
            @Html.ActionLink("Mark presence", "MarkLabPresence", new {  labId = item.LabId  }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) 
        </td>
    </tr>
}

</table>

Aips/Views/Assistant/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2>Dashboard</h2>

<div class="row col-md-12">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Schedules</div>
            <div class="panel-body">
                <ul class="list-group">
                    @Html.ActionLink("New schedule", "NewSchedule", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Check existing schedules", "CheckSchedules", null, new { @class = "list-group-item list-group-item-warning" })
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Exams</div>
            <div class="panel-body">
                <ul class="list-group">
                    @Html.ActionLink("Schedule exam", "ScheduleExam", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Check scheduled exams", "CheckScheduledExams", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Store exam PDF", "StoreExamPDF", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Check uploaded exams", "CheckUploadedExams", null, new { @class = "list-group-item" })
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Professors</div>
            <div class="panel-body">
                <ul class="list-group">
                    @Html.ActionLink("Assign subject to professor", "AssignSubjectToProfessor", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Check assigned subjects", "CheckAssignedSubjects", null, new { @class = "list-group-item" })
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Assistants</div>
            <div class="panel-body">
                <ul class="list-group">
                    @Html.ActionLink("Assign subject to assistant", "AssignSubjectToAssistant", null, new { @class = "list-group-item" })
                </ul>
            </div>
        </div>
    </div>
</div>

Aips/Views/Assistant/MarkLabPresence.cshtml
@model IEnumerable<EntityClasses.MarkLabPresenceViewModel>

@{
    ViewBag.Title = "MarkLabPresence";
    EntityClasses.Lab lab = ViewBag.Lab;
}
<script src="~/Scripts/MarkLabPresence.js"></script>
<h2>Mark lab presence - @lab.Subject.Title (@lab.ScheduledClassroom.SchoolDay.Name @lab.ScheduledClassroom.ScheduleStart.ToShortTimeString() - @lab.ScheduledClassroom.ScheduleEnd.ToShortTimeString())</h2>
<h3>@DateTime.Today.ToShortDateString()</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WasPresent)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentFirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentLastName)
        </td>
        <td>
            @Html.CheckBoxFor(modelItem => item.WasPresent, new { onchange = "markPresence(this, '" + item.StudentId + "')" })
        </td>
    </tr>
}
</table>

@using (Html.BeginForm("MarkLabPresence", "Assistant", null, FormMethod.Post, new { name = "idsForm" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="ids" value="" id="presentIds"/>
    <input type="button" value="Save" class="btn btn-default" onclick="savePresence()" />
}